In [1]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

## MAE

In [4]:
def mae(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    print("Total Error: ", total_error)
    mae = total_error / len(y_true)
    print('MAE: ', mae)

In [5]:
mae(y_true, y_predicted)

Total Error:  2.5
MAE:  0.5


In [6]:
np.mean(np.abs(y_predicted - y_true))

0.5

## MSE

In [7]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += pow(abs(yt - yp),2)
    print("Total Error: ", total_error)
    mse = total_error / len(y_true)
    print('MSE: ', mse)

In [8]:
mse(y_true, y_predicted)

Total Error:  1.83
MSE:  0.366


## Binary Cross Entropy // LogLoss

In [9]:
np.log([0])

C:\Users\sarim\AppData\Local\Temp\ipykernel_18828\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [10]:
np.log([0.000000000000000000000000000001])  # Very close to 0

array([-69.07755279])

In [11]:
epsilon = 1e-15

In [12]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [13]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [14]:
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [15]:
np.log(y_predicted)   # WRONG

C:\Users\sarim\AppData\Local\Temp\ipykernel_18828\815880036.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(y_predicted)


array([  0.,   0., -inf, -inf,   0.])

In [17]:
logloss = -np.mean(y_true*np.log(y_predicted_new)+ (1-y_true)*np.log(1-y_predicted_new))
logloss

17.2696280766844

In [18]:
def logloss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i, epsilon) for i in y_predicted]
    y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    logloss = -np.mean(y_true*np.log(y_predicted_new)+ (1-y_true)*np.log(1-y_predicted_new))
    return logloss

In [19]:
logloss(y_true, y_predicted)

17.2696280766844